services:
  labcode-bot:
    build: .
    container_name: labcode-bot
    restart: unless-stopped
    networks:
      - labcode-network
    env_file:
      - .env
networks:
  labcode-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16